const SUCCESS = 200;
const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const DOCUMENTNOTFOUND_ERROR = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  SUCCESS,
  BAD_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  DOCUMENTNOTFOUND_ERROR,
  INTERNAL_SERVER_ERROR,
};
